### PR TITLE
Native FreeRTOS port

### PR DESCRIPTION
**Pull request by sn00pster**
Hi,

Here's a native FreeRTOS port of the OS layer.

### CODE REVIEW

**Comment by sn00pster** [comment]
Where are the coding rules I can't seem to find them (maybe I'm not looking hard enough), point me in the right direction and I'll make any necessary changes.

I tried to make it as close to the coding style used in the cmsis port as I could.

**Comment by MaJerle** [comment]
There are in fact no any. Please refer to cmsis_os port for style like this:

- File name is not template anymore, change file name on top of file and description of it
- Remove function/typedef comments from port functions, to make it easier and faster to read. Comments are available in template file, which is also used for documentation generation.
- Below some code examples

```
//No brackets, check for spaces between keywords
return osMessagePut(*b, (uint32_t)m, 0) == osOK;

//Your example
return(xSemaphoreGiveRecursive(*p)==pdPASS);
//Should be
return xSemaphoreGiveRecursive(*p) == pdPASS;
```

```
//Curly opening bracket on the same line as if statement
//and proper spaces alignment
if (evt.status == osEventMessage) {         /* Did we get a message? */
    *m = evt.value.p;                       /* Set value */
    return 1;
}
```

and so on.
In the meantime I will prepare one rules for all my libraries.

Thank you for your effort to this library.

BTW, which microcontroller do you use?

**Comment by sn00pster** [comment]
Cool, that will be handy.  Will try to fix up the request for you later on tonight.

No worries, thank you for providing this and the other libraries you've spent time developing, much appreciated, happy to contribute to this great piece of code!

I'm using a STM32, I know I could use the CMSIS layer but I prefer using the native rtos api.  I use STM32 processors in my day job, but I've done a small design of my own with the ESP-12F and couldn't face writing an AT parser *properly* for it so I was very pleased when I came across yours!

**Comment by sn00pster** [comment]
Any better?  I'm having trouble with tabbing in the header file, mine are obviously set up to work differently than yours.

**Comment by MaJerle** [comment]
I did merge and updated some code parts. Please do second review, specially around message box and `xQueueSendFromISR` function. Also, with thread management, please make sure it handles properly if identifier `t` is `NULL`.

http://majerle.eu/documentation/esp_at/html/group___e_s_p___s_y_s.html#ga8dcf0ceda8933766f5c13c98454f3827

**Pull request merged**
