### PR TITLE
Optimize lwespi_is_valid_conn_ptr function

### PR DESCRIPTION
**Pull request by niedong**
A small optimize in `lwespi_is_valid_conn_ptr` function

### CODE REVIEW

**Comment by MaJerle** [comment]
Thanks for contribution. Did you check outcome of this correction?

Modulus of non-power-of-2 can be very very slow, depends on arch and compiler of course.

**Comment by niedong** [comment]
I changed to another way of deciding the conn ptr is aligned correctly, but that may involve division since `sizeof(lwesp_conn_t)` is not a power of 2 and cannot be done by shifting. To know that there may be involving division, I tested a simple code on vs2017 and opened disassembly window.
image
Here `test` is a struct with three ints(`sizeof(test)` is 12) and you can see that the result is divided by 0Ch.
The function should be correct with input. I test with `lwesp_netconn_write` and nothing went wrong.
What do you think?

**Comment by niedong** [comment]
（I'm not an expert in computer architecture）

**Comment by MaJerle** [comment]
Question is not if it will work, but if your corrections bring any improvements. So far I'm not that sure and further tests would need to prove it.

**Comment by niedong** [comment]
Yes, I agree. I'll close this pr.

**Pull request closed without merging**
